/* evdev-dump-codes.h — GENERATED by gen_evdev_probe_codes.py; do not edit.
 * Regenerate: python3 regression/caps/gen_evdev_probe_codes.py --platform <dir>
 * Values are kernel ABI (input-event-codes.h), restricted to core/caps.py vocab —
 * the same tables spliced into evdev-probe.py, so both capture tools agree. */
struct code_name { int code; const char *name; };

static const struct code_name PF_BTN_TAB[] = {
    { 0x120, "BTN_TRIGGER" },
    { 0x121, "BTN_THUMB" },
    { 0x130, "BTN_A" },
    { 0x131, "BTN_B" },
    { 0x132, "BTN_C" },
    { 0x133, "BTN_X" },
    { 0x134, "BTN_Y" },
    { 0x135, "BTN_Z" },
    { 0x136, "BTN_TL" },
    { 0x137, "BTN_TR" },
    { 0x138, "BTN_TL2" },
    { 0x139, "BTN_TR2" },
    { 0x13a, "BTN_SELECT" },
    { 0x13b, "BTN_START" },
    { 0x13c, "BTN_MODE" },
    { 0x13d, "BTN_THUMBL" },
    { 0x13e, "BTN_THUMBR" },
    { 0x220, "BTN_DPAD_UP" },
    { 0x221, "BTN_DPAD_DOWN" },
    { 0x222, "BTN_DPAD_LEFT" },
    { 0x223, "BTN_DPAD_RIGHT" },
};
#define PF_BTN_TAB_LEN (sizeof(PF_BTN_TAB) / sizeof(PF_BTN_TAB[0]))

static const struct code_name PF_KEY_TAB[] = {
    { 0x1, "KEY_ESC" },
    { 0x1c, "KEY_ENTER" },
    { 0x66, "KEY_HOME" },
    { 0x72, "KEY_VOLUMEDOWN" },
    { 0x73, "KEY_VOLUMEUP" },
    { 0x74, "KEY_POWER" },
    { 0x8b, "KEY_MENU" },
    { 0x9e, "KEY_BACK" },
    { 0xac, "KEY_HOMEPAGE" },
};
#define PF_KEY_TAB_LEN (sizeof(PF_KEY_TAB) / sizeof(PF_KEY_TAB[0]))

static const struct code_name PF_ABS_TAB[] = {
    { 0x0, "ABS_X" },
    { 0x1, "ABS_Y" },
    { 0x2, "ABS_Z" },
    { 0x3, "ABS_RX" },
    { 0x4, "ABS_RY" },
    { 0x5, "ABS_RZ" },
    { 0x6, "ABS_THROTTLE" },
    { 0x7, "ABS_RUDDER" },
    { 0x9, "ABS_GAS" },
    { 0xa, "ABS_BRAKE" },
    { 0x10, "ABS_HAT0X" },
    { 0x11, "ABS_HAT0Y" },
    { 0x12, "ABS_HAT1X" },
    { 0x13, "ABS_HAT1Y" },
};
#define PF_ABS_TAB_LEN (sizeof(PF_ABS_TAB) / sizeof(PF_ABS_TAB[0]))
