#!/usr/bin/env python3
"""Device descriptor staging for app-runtime profiles (tsp-f3fm.202.1 R1 / B3).

devices/<id>/capabilities.toml reaches the image as a platform-owned input ONLY for the
profiles that receive the app-runtime contract (A133-open). profile.py emits
PF_DEVICE_DESCRIPTOR_ID + PF_DEVICE_DESCRIPTOR_SHA256 for exactly those profiles and every
other build-arg / env / resolve output is byte-identical to platform main 6bd782e.
"""
import copy
import hashlib
import importlib.util
import os
import pathlib
import re
import subprocess
import sys
import tempfile
import tomllib
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location("pf_profile_descriptor", ROOT / "core/profile.py")
profile = importlib.util.module_from_spec(spec)
spec.loader.exec_module(profile)

A133_OPEN_PROFILES = {
    "a133-open",
    "a133-open-7x-gpu",
    "a133-open-7x-gpu-noradio",
    "a133-open-7x-gpu-spl-trace",
}
DESCRIPTOR_KEYS = ("PF_DEVICE_DESCRIPTOR_ID", "PF_DEVICE_DESCRIPTOR_SHA256")
DESCRIPTOR_PATH = ROOT / "devices/a133/capabilities.toml"
LOCK_SHA = re.compile(r"\b[0-9a-f]{40}\b")
DESCRIPTOR_LINE = re.compile(r"^PF_DEVICE_DESCRIPTOR_(ID|SHA256)=.*\n", re.M)
PLATFORM_RUNTIME_LINE = re.compile(
    r"^PF_(?:STEAMLINK_FFMPEG59_MODE|FFMPEG_[A-Z0-9_]+)=.*\n", re.M)

# SHA-256 of each `core/profile.py <command>` stdout, generated by running the UNCHANGED
# platform main 6bd782e tree (git archive) before descriptor staging existed. Every 40-hex
# platform.lock SHA is masked to "<sha>" so a lock move (gpu-14, B5) does not invalidate the
# table; the descriptor lines are removed before hashing (and counted separately below), so a
# match proves the ONLY change to any output is the two added descriptor build args on the
# A133-open profiles. A deliberate profile change regenerates this with a stated reason.
# tsp-op5a.440.1.1 deliberately changes only a133-open-7x-gpu buildargs/resolve to add its
# branch-only exact Gamescope package selector and platform-locked materialized source-tree
# digest; every unrelated profile digest stays fixed.
PRE_DESCRIPTOR_DIGESTS = {
    ("a133", "buildargs dev"): "303b91d08e13a5c705ef62df98f40435fd0a647858047bd30674dbd3cd24e169",
    ("a133", "buildargs release"): "de407dfc1948e12c1cd54f71a49c9ca4a34fb419dd7312ca5467a3eb44be7a26",
    ("a133", "env"): "3e5af820f51e69426e838d63215725253114f62f7f1acf511d0feb0f5bc2b61d",
    ("a133", "resolve"): "47df1a27fa13f5efbb1a8156c0381a6c25abbc707813a0e6740377d514b1cf21",
    ("a133-open", "buildargs dev"): "a2e8fd9585a5a813bd10487630431077f25568396f859cac67ccf834cd24e480",
    ("a133-open", "buildargs release"): "eaba258af598f4838576017bb5c522a17e378700ac8d6f64a266ab143e199d0b",
    ("a133-open", "env"): "2e176603fb313a1a4fc61a1728431cb2e117cff665478196219832d59be0988e",
    ("a133-open", "resolve"): "25a1fa2b5cdf4b1340962d66d9a1bfbae6047d01f870b9a0bc5da948b32d763d",
    ("a133-open-7x", "buildargs dev"): "68baff32eb3fe6a210093125fa53f29646eff6cd52450be6eb16c19a3a05cf55",
    ("a133-open-7x", "buildargs release"): "508d6b9703a852606a4c380a6194c303a3b3a03d2dbeb481ad060468dc7b95a5",
    ("a133-open-7x", "env"): "b377507c70e95156b3956597d6f66e582549419cbca9455aeaa512851e4cc018",
    ("a133-open-7x", "resolve"): "e4e792f18991106e2d69f29b3000e0915ff84f44e568ece91859d7bd00128222",
    ("a133-open-7x-gpu", "buildargs dev"): "8e4e375af0ac305f70e4f7db2cd863361ee43838b48846a5ed5eb398a2639a50",
    ("a133-open-7x-gpu", "buildargs release"): "b801611b1daf3bddac405647ddcf25eacfad0b987da4e817ccbe623da2ee03f0",
    ("a133-open-7x-gpu", "env"): "d8f9bd9b1fc5159735ae4a9fc2ed413bf2db17a46615e49651020d0b1d7a2f3a",
    ("a133-open-7x-gpu", "resolve"): "ff485795bf2791ddf1c844cd20478a6c59633b639ff52071056927708fd8d91f",
    ("a133-open-7x-gpu-noradio", "buildargs dev"): "5bcabe3cfbfb73f7524044f6516d96cdcc277ce4cfcb9fb7f644c130f8ea03b9",
    ("a133-open-7x-gpu-noradio", "buildargs release"): "e1f84199f439af205ea93aec746dda90988b9fe0dc1bececc558ce0c7475873b",
    ("a133-open-7x-gpu-noradio", "env"): "d3efc6a7693b973a9581d5115c61b2cd3b53f8f291b008d930cb72351cdbd5a8",
    ("a133-open-7x-gpu-noradio", "resolve"): "bb7098a57d2b0c08e976a4404c66e56bd3284d51b8fdb89cc4b5bb289a45ec00",
    ("a133-open-7x-gpu-spl-trace", "buildargs dev"): "a6c33cf25aca86bd9311367a3371b3870c63c1484aeb0dfa015eec38827b8333",
    ("a133-open-7x-gpu-spl-trace", "buildargs release"): "02a30fb82d23a5bf500e4d7e1c1b9e1a18254cfeb0acd416181bcb5e1f79d958",
    ("a133-open-7x-gpu-spl-trace", "env"): "dc53661bd070044973beca31bc3dbd4c13f3d50ea7b43a6a3c2cadfad63508fd",
    ("a133-open-7x-gpu-spl-trace", "resolve"): "30ababe1f9896502967f2c6eadde41080851eca6d7cd9c04ae32f34320215a31",
    ("a133-owned", "buildargs dev"): "a8126cdffa5588d8e9703c9ba622c11c07d89c528daea13baf948a4f3019d496",
    ("a133-owned", "buildargs release"): "2a7dbed21687be103076c0694590421752477cc9865a88e371457f4fef964f2c",
    ("a133-owned", "env"): "26ff80b05a4c64e5b27a0fe8ebb641fcd80dbe9b44f7bf1e558d3c1a3b6bd4cc",
    ("a133-owned", "resolve"): "0058b5e7da4c186a335f162f86cd9af66715348c84bdd74764ad323112534aee",
    ("a523", "buildargs dev"): "165a85e6ef0d4d31a7ef74fd3dc3380c44d72bce1f5f28fef9de5e0c99c4bf8d",
    ("a523", "buildargs release"): "621213a75a643b89fd149b436e5a186684814d92190b95dfaea9cfd39bf0401e",
    ("a523", "env"): "0cdab9ca515b04fa806f75deb5c310cf7fc7b56dc2b657f8c278e97f8aa3d308",
    ("a523", "resolve"): "999aaab6c955da6ec5ad45e410e062aaa7eb7159b230b6a13a89f3b78deec78d",
    ("sdm845", "buildargs dev"): "e71ad66411037951fa9bfd78e3fc2d15ced3ae4aac5c533fc57814c5760982f8",
    ("sdm845", "buildargs release"): "c7fe2e1236623c1254e77367c3d72fcea7d1d0390734a44adb37c824db1df407",
    ("sdm845", "env"): "45ff04448acae2caf3478ef2b8550110e668c89cb99a6e8691f96ea8b3692000",
    ("sdm845", "resolve"): "76a7d84f66ed135b6e76da30d7fd5a040b0743e884e9a41d465e955d89416810",
}


def run_profile(*argv):
    return subprocess.run(
        [sys.executable, "-B", str(ROOT / "core/profile.py"), *argv],
        check=True, capture_output=True, text=True).stdout


# --- Mirror of the runtime `Descriptor` serde shape (runtime 0589fcfa,
# crates/pocketforge/src/descriptor.rs). serde+toml ignore unknown fields but reject a
# missing required field or a present field of the wrong type; this mirrors exactly that.
# It is NOT the Rust loader: the loader itself is exercised by B4 against the installed file.
I32 = (-(2 ** 31), 2 ** 31 - 1)


def _fields(test, where, table, required, optional):
    test.assertIsInstance(table, dict, where)
    for name, kind in required.items():
        test.assertIn(name, table, f"{where}: missing required {name}")
    for name, kind in {**required, **optional}.items():
        if name in table:
            kind(test, f"{where}.{name}", table[name])


def _str(test, where, value):
    test.assertIsInstance(value, str, where)


def _int_in(bounds):
    def check(test, where, value):
        test.assertTrue(isinstance(value, int) and not isinstance(value, bool), where)
        test.assertTrue(bounds[0] <= value <= bounds[1], where)
    return check


def _axis(test, where, value):
    i32 = _int_in(I32)
    _fields(test, where, value, {"min": i32, "max": i32},
            {"flat": i32, "fuzz": i32, "resolution": i32, "value": i32})


def _rows(row_check):
    def check(test, where, value):
        test.assertIsInstance(value, list, where)
        for index, row in enumerate(value):
            row_check(test, f"{where}[{index}]", row)
    return check


def _match(test, where, value):
    _fields(test, where, value, {"evdev_name": _str, "vid": _str, "pid": _str}, {})


def _identity(test, where, value):
    _fields(test, where, value,
            {"id": _str, "manufacturer": _str, "model": _str, "sdl_guid": _str},
            {"codename": _str, "match": _match})


def _input(test, where, value):
    _fields(test, where, value,
            {"id": _str, "kind": _str, "ev_type": _str, "code": _str},
            {name: _str for name in ("semantics", "class", "source", "label", "skin_part", "ui")}
            | {"range": _axis, "x": _axis, "y": _axis})


def _matrix(test, where, value):
    test.assertIsInstance(value, list, where)
    for row in value:
        test.assertIsInstance(row, list, where)
        for cell in row:
            _int_in(I32)(test, where, cell)


def _sensor(test, where, value):
    _fields(test, where, value, {"id": _str, "kind": _str},
            {"iio_device": _str, "units": _str, "ui": _str, "mount_matrix": _matrix})


def _actuator(test, where, value):
    _fields(test, where, value, {"id": _str, "kind": _str},
            {"count": _int_in((0, 2 ** 32 - 1)), "controller": _str, "sysfs": _str})


def assert_runtime_descriptor_shape(test, document):
    _fields(test, "descriptor", document, {"identity": _identity},
            {"accept_default": _str, "inputs": _rows(_input),
             "sensors": _rows(_sensor), "actuators": _rows(_actuator)})


class DeviceDescriptorStagingTest(unittest.TestCase):
    def test_descriptor_args_are_emitted_exactly_for_a133_open(self):
        want_sha = hashlib.sha256(DESCRIPTOR_PATH.read_bytes()).hexdigest()
        observed = set()
        for dev_id in profile.list_devices():
            for variant in ("dev", "release"):
                args, _, missing = profile.build_args(dev_id, variant)
                emitted = {key: args[key] for key in DESCRIPTOR_KEYS if key in args}
                if dev_id in A133_OPEN_PROFILES:
                    observed.add(dev_id)
                    self.assertEqual(emitted, {
                        "PF_DEVICE_DESCRIPTOR_ID": "a133",
                        "PF_DEVICE_DESCRIPTOR_SHA256": want_sha,
                    }, (dev_id, variant))
                    self.assertEqual(missing, [], (dev_id, variant))
                else:
                    self.assertEqual(emitted, {}, (dev_id, variant))
        self.assertEqual(observed, A133_OPEN_PROFILES)

    def test_descriptor_selection_follows_the_app_runtime_contract(self):
        for dev_id in profile.list_devices():
            merged, _ = profile.resolve(dev_id)
            descriptor = profile._resolve_device_descriptor(merged)
            self.assertEqual(descriptor is not None, "app_runtime" in merged, dev_id)
            if descriptor is not None:
                self.assertEqual(descriptor["path"], "devices/a133/capabilities.toml", dev_id)

    def test_every_profile_output_is_byte_identical_to_pre_descriptor_main(self):
        self.assertEqual({dev for dev, _ in PRE_DESCRIPTOR_DIGESTS}, set(profile.list_devices()))
        commands = {
            "buildargs dev": ("buildargs", "{dev}", "dev"),
            "buildargs release": ("buildargs", "{dev}", "release"),
            "env": ("env", "{dev}"),
            "resolve": ("resolve", "{dev}"),
        }
        for (dev_id, name), digest in PRE_DESCRIPTOR_DIGESTS.items():
            out = run_profile(*(part.format(dev=dev_id) for part in commands[name]))
            added = DESCRIPTOR_LINE.findall(out)
            expected_added = 2 if (dev_id in A133_OPEN_PROFILES and name.startswith("buildargs")) else 0
            self.assertEqual(len(added), expected_added, (dev_id, name))
            # Later platform-runtime payloads are independently tested and do
            # not alter this historical descriptor-only baseline.
            stripped = LOCK_SHA.sub(
                "<sha>", PLATFORM_RUNTIME_LINE.sub("", DESCRIPTOR_LINE.sub("", out)))
            self.assertEqual(hashlib.sha256(stripped.encode()).hexdigest(), digest, (dev_id, name))

    def test_descriptor_emission_is_deterministic(self):
        first = run_profile("buildargs", "a133-open", "dev")
        second = run_profile("buildargs", "a133-open", "dev")
        self.assertEqual(first, second)
        lines = [line for line in first.splitlines() if line.startswith("PF_DEVICE_DESCRIPTOR_")]
        self.assertEqual(lines, [
            "PF_DEVICE_DESCRIPTOR_ID=a133",
            "PF_DEVICE_DESCRIPTOR_SHA256=" + hashlib.sha256(DESCRIPTOR_PATH.read_bytes()).hexdigest(),
        ])

    def test_staged_descriptor_parses_with_the_runtime_descriptor_shape(self):
        document = tomllib.loads(DESCRIPTOR_PATH.read_text(encoding="utf-8"))
        assert_runtime_descriptor_shape(self, document)
        self.assertEqual(document["identity"]["id"], "a133")
        self.assertTrue(document["inputs"], "input rows are required for the input capability")
        # The shape mirror must actually reject what serde would reject.
        for mutate in (
            lambda d: d["identity"].pop("sdl_guid"),
            lambda d: d["identity"]["match"].pop("evdev_name"),
            lambda d: d["inputs"][0].__setitem__("code", 304),
            lambda d: d.__setitem__("actuators", [{"id": "x", "kind": "led", "count": -1}]),
        ):
            broken = copy.deepcopy(document)
            mutate(broken)
            with self.assertRaises(AssertionError):
                assert_runtime_descriptor_shape(self, broken)

    def test_descriptor_resolution_fails_closed(self):
        merged, _ = profile.resolve("a133-open")
        good = DESCRIPTOR_PATH.read_bytes()
        with tempfile.TemporaryDirectory() as tmp:
            root = pathlib.Path(tmp)
            original_root = profile.ROOT
            profile.ROOT = str(root)
            try:
                with self.assertRaisesRegex(profile.ProfileSchemaError, "no devices/"):
                    profile._resolve_device_descriptor(merged)
                (root / "devices/a133").mkdir(parents=True)
                descriptor = root / "devices/a133/capabilities.toml"
                descriptor.write_bytes(good.replace(b'id           = "a133"', b'id           = "a523"', 1))
                with self.assertRaisesRegex(profile.ProfileSchemaError, r"\[identity\]\.id"):
                    profile._resolve_device_descriptor(merged)
                descriptor.write_bytes(b"[identity\n")
                with self.assertRaisesRegex(profile.ProfileSchemaError, "does not parse"):
                    profile._resolve_device_descriptor(merged)
                descriptor.unlink()
                (root / "elsewhere.toml").write_bytes(good)
                os.symlink(root / "elsewhere.toml", descriptor)
                with self.assertRaisesRegex(profile.ProfileSchemaError, "regular file"):
                    profile._resolve_device_descriptor(merged)
                descriptor.unlink()
                descriptor.write_bytes(good)
                self.assertEqual(profile._resolve_device_descriptor(merged)["sha256"],
                                 hashlib.sha256(good).hexdigest())
                # A variant's own descriptor wins over its base's, and must name itself.
                (root / "devices/a133-open").mkdir()
                (root / "devices/a133-open/capabilities.toml").write_bytes(good)
                with self.assertRaisesRegex(profile.ProfileSchemaError, "must be 'a133-open'"):
                    profile._resolve_device_descriptor(merged)
                # validate() surfaces the refusal instead of emitting build args.
                errors, _ = profile.validate("a133-open", profile.load_lock())
                self.assertTrue(any("a133-open" in error and "identity" in error
                                    for error in errors), errors)
                errors, _ = profile.validate("a523", profile.load_lock())
                self.assertEqual(errors, [])
            finally:
                profile.ROOT = original_root
            non_open, _ = profile.resolve("a523")
            self.assertIsNone(profile._resolve_device_descriptor(non_open))


if __name__ == "__main__":
    unittest.main()
